ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChillLancer_RazorPage.Model.AccountDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ChillLancer_RazorPage.Models;

namespace ChillLancer_RazorPage.Pages.Accounts
{
    public class CreateModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CreateModel(HttpClient httpClient,
            IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _httpClient = httpClient;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public AccountCreateDto Account { get; set; } = default!;
        public string ErrorMessage { get; set; }

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var result = await _httpClient.PostAsJsonAsync(EndpointConst.baseUrl + EndpointConst.account, Account);
            var response = await result.Content.ReadFromJsonAsync<ResponseModel> ();
            if (result.IsSuccessStatusCode)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                ErrorMessage = response.value.message;
                return Page();
            }
        }

    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Accounts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChillLancer_RazorPage.Model.AccountDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ChillLancer_RazorPage.Models;

namespace ChillLancer_RazorPage.Pages.Accounts
{
    public class DeleteModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DeleteModel(HttpClient httpClient, IHttpContextAccessor httpContextAccessor)
        {
            _httpClient = httpClient;
            _httpContextAccessor = httpContextAccessor;

            //var token = _httpContextAccessor.HttpContext?.Session.GetString("CustomerToken") ??
            //            _httpContextAccessor.HttpContext?.Session.GetString("EmpToken");

            //if (!string.IsNullOrEmpty(token))
            //{
            //    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            //}
        }

        [BindProperty]
        public AccountModel Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = new AccountModel();
                /*await _httpClient.GetAsync(ApplicationEndpoint.GetByIdEndPoint + id)*/

            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = new AccountModel();
            /*await _httpClient.GetAsync(ApplicationEndpoint.GetByIdEndPoint + id)*/

            if (account != null)
            {
                Account = account;
                var response = await _httpClient.DeleteAsync("");
                    //await _httpClient.DeleteAsync(ApplicationEndpoint.GetByIdEndPoint + id);
                if (response.IsSuccessStatusCode)
                {
                    // Successfully deleted
                }
                else
                {
                    // Handle error
                }
            }

            return RedirectToPage("./Index");
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChillLancer_RazorPage.Model.AccountDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ChillLancer_RazorPage.Models;

namespace ChillLancer_RazorPage.Pages.Accounts
{
    public class DetailsModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DetailsModel(HttpClient httpClient, IHttpContextAccessor httpContextAccessor)
        {
            _httpClient = httpClient;
            _httpContextAccessor = httpContextAccessor;

            //var token = _httpContextAccessor.HttpContext?.Session.GetString("CustomerToken") ??
            //            _httpContextAccessor.HttpContext?.Session.GetString("EmpToken");

            //if (!string.IsNullOrEmpty(token))
            //{
            //    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            //}
        }

        public AccountModel Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = new AccountModel();
            /*await _httpClient.GetAsync(ApplicationEndpoint.GetByIdEndPoint + id)*/
            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Accounts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChillLancer_RazorPage.Model.AccountDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ChillLancer_RazorPage.Models;

namespace ChillLancer_RazorPage.Pages.Accounts
{
    public class EditModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public EditModel(HttpClient httpClient, IHttpContextAccessor httpContextAccessor)
        {
            _httpClient = httpClient;
            _httpContextAccessor = httpContextAccessor;

            //var token = _httpContextAccessor.HttpContext?.Session.GetString("CustomerToken") ??
            //            _httpContextAccessor.HttpContext?.Session.GetString("EmpToken");

            //if (!string.IsNullOrEmpty(token))
            //{
            //    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            //}
        }

        [BindProperty]
        public AccountModel Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = new AccountModel();
            /*await _httpClient.GetAsync(ApplicationEndpoint.GetByIdEndPoint + id)*/
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //var api = ApplicationEndpoint.Endpoint + string";
            //try
            //{
            //    var content = new StringContent(JsonConvert.SerializeObject(Service), Encoding.UTF8, "application/json");
            //    var result = await _httpClient.PutAsync(api, content);
            //    if (result.StatusCode == System.Net.HttpStatusCode.NoContent)
            //        return RedirectToPage("./Index");
            //}
            //catch (HttpRequestException ex)
            //{
            //    ModelState.AddModelError(string.Empty, $"{ex.Message}");
            //    //return Page();
            //}

            return RedirectToPage("./Index");
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Accounts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChillLancer_RazorPage.Model.AccountDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ChillLancer_RazorPage.Models;
using Newtonsoft.Json;
using System.Text.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace ChillLancer_RazorPage.Pages.Accounts
{
    public class IndexModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public IndexModel(HttpClient httpClient, IHttpContextAccessor httpContextAccessor)
        {
            _httpClient = httpClient;
            _httpContextAccessor = httpContextAccessor;

            //var token = _httpContextAccessor.HttpContext?.Session.GetString("CustomerToken") ??
            //            _httpContextAccessor.HttpContext?.Session.GetString("EmpToken");

            //if (!string.IsNullOrEmpty(token))
            //{
            //    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            //}
        }
        [BindProperty]
        public List<AccountDto> Accounts { get; set; } = new List<AccountDto>();

        // ... other code

        public async Task OnGetAsync()
        {
            try
            {
                var result = await _httpClient.GetAsync(EndpointConst.baseUrl + EndpointConst.account);

                if (result.IsSuccessStatusCode)
                {
                    var jsonString = await result.Content.ReadAsStringAsync();
                    Console.WriteLine("Raw JSON Response: " + jsonString);

                    var response = JsonSerializer.Deserialize<ResponseModel>(jsonString,
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    if (response is not null && response.value is not null && response.value.data is not null)
                    {
                        var dataJson = JsonSerializer.Serialize(response.value.data);
                        Console.WriteLine("Raw JSON Data: " + dataJson);

                        try
                        {
                            Accounts = JsonSerializer.Deserialize<List<AccountDto>>(dataJson,
                                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine("Error deserializing data: " + ex.Message);
                            Console.WriteLine("Stack Trace: " + ex.StackTrace);
                        }
                    }
                    else
                    {
                        Console.WriteLine("Response or data is null.");
                    }
                }
                else
                {
                    Console.WriteLine($"API call failed with status: {result.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
                Console.WriteLine("Stack Trace: " + ex.StackTrace);
            }
        }


    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Admin/Management/Accounts.cshtml.cs
using ChillLancer_RazorPage.Models.ResponseModels;
using ChillLancer_RazorPage.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChillLancer_RazorPage.Pages.Admin.Management
{
    public class AccountsModel : PageModel
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;

        public AccountsModel(IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _httpClient = httpClientFactory.CreateClient();
            _configuration = configuration;
        }

        public List<AccountVM> AccountsList { get; set; } = [];

        [BindProperty]
        public AccountVM AccountObj { get; set; } = new AccountVM();

        [BindProperty]
        public bool IsEdit { get; set; } = false;

        //==========================================================================================
        public async Task OnGetAsync()
        {
            var serverUrl = _configuration["ServerUrl"];
            var apiUrl = $"{serverUrl}/api/account/odata";

            try
            {
                var response = await _httpClient.GetFromJsonAsync<List<AccountVM>>(apiUrl);
                if (response != null)
                {
                    AccountsList = response;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Fetch categories error: " + ex.Message);
            }
        }

        public async Task<IActionResult> OnPostSaveAsync()
        {
            var serverUrl = _configuration["ServerUrl"];
            var apiUrl = $"{serverUrl}/api/account";

            if (!IsEdit)
            {
                var response = await _httpClient.PostAsJsonAsync(apiUrl, AccountObj);
                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(string.Empty, "Add New Failed!");
                    await OnGetAsync();
                    return Page();
                }
            }
            else
            {
                var request = new HttpRequestMessage(new HttpMethod("PUT"), apiUrl)
                {
                    Content = JsonContent.Create(AccountObj)
                };
                var response = await _httpClient.SendAsync(request);
                var message = await response.Content.ReadAsStringAsync();
                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(string.Empty, message);
                    await OnGetAsync();
                    return Page();
                }
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            var serverUrl = _configuration["ServerUrl"];
            var apiUrl = $"{serverUrl}/api/account";

            var response = await _httpClient.DeleteAsync($"{apiUrl}/{id}");
            var message = await response.Content.ReadAsStringAsync();
            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError(string.Empty, message);
            }
            return RedirectToPage();
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Admin/Management/Proposals.cshtml.cs
using ChillLancer_RazorPage.Models;
using ChillLancer_RazorPage.Pages.Accounts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http;

namespace ChillLancer_RazorPage.Pages.Admin.Management
{
    public class ProposalsModel(HttpClient httpClient, IHttpContextAccessor httpContextAccessor) : PageModel
    {
        private readonly HttpClient _httpClient = httpClient;
        private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
        public IList<ProposalModel> Proposals { get; set; } = [];
        public async Task OnGetAsync(Guid id)
        {
            await LoadProposalListAsync(id);
        }
        private async Task LoadProposalListAsync(Guid id)
        {
            string requestUrl = $"{EndpointConst.baseUrl}{EndpointConst.proposal}{id}";
            var proposals = await _httpClient.GetAsync(requestUrl);
            Proposals = proposals.IsSuccessStatusCode
                ? await proposals.Content.ReadFromJsonAsync<List<ProposalModel>>() ?? [] : [];
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Admin/Management/Transactions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChillLancer_RazorPage.Pages.Admin.Management
{
    public class TransactionsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Admin/Management/Projects.cshtml
@page
@model ChillLancer_RazorPage.Pages.Admin.Management.ProjectsModel
@{
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Projects Configuration</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-page="/Dashboard">Dashboard</a></li>
                <li class="breadcrumb-item">System Configuration</li>
                <li class="breadcrumb-item active">Projects</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-sm">
                                <h5 class="card-title">Projects</h5>
                            </div>
                            <div class="col-sm text-end ">
                                <button id="btnAddNew" type="button" class="btn btn-md btn-primary" data-bs-toggle="modal" data-bs-target="#projectsModal">
                                    <i class="bi bi-plus-circle me-1"></i>Add New
                                </button>
                            </div>
                        </div>

                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Budget</th>
                                    <th>Duration</th>
                                    <th>StartDate</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var proj in Model.ProjectsList)
                                {
                                    <tr>
                                        <td>@proj.Title</td>
                                        <td>@proj.Budget</td>
                                        <td>@proj.Duration</td>
                                        <td>@proj.StartDate</td>
                                        <td>@proj.Status</td>
                                        <td>
                                            <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#projectModal"
                                                    data-id="@proj.Id" data-title="@proj.Title" data-budget="@proj.Budget" data-duration="@proj.Duration" data-status="@proj.Status">
                                                Edit
                                            </button>
                                            <form method="post" asp-page-handler="Delete" style="display:inline">
                                                <input type="hidden" name="id" value="@proj.Id" />
                                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure to delete?')">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                        <div class="modal fade" id="projectModal" tabindex="-1">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <form method="post" asp-page-handler="Save">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Project Form</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" id="isEdit" asp-for="IsEdit" />
                                            <input type="hidden" id="projectId" asp-for="ProjectObj.Id" value="" />
                                            <div class="mb-3">
                                                <label asp-for="ProjectObj.Title" class="form-label">Title</label>
                                                <input type="text" class="form-control" id="projectTitle" asp-for="ProjectObj.Title" required />
                                            </div>
                                            <div class="mb-3">
                                                <label asp-for="ProjectObj.Budget" class="form-label">Budget</label>
                                                <input type="text" class="form-control" id="projectBudget" asp-for="ProjectObj.Budget" required />
                                            </div>
                                            <div class="mb-3">
                                                <label asp-for="ProjectObj.Duration" class="form-label">Duration</label>
                                                <input type="text" class="form-control" id="projectDuration" asp-for="ProjectObj.Duration" required />
                                            </div>
                                            <div class="mb-3" id="statusGroup">
                                                <label asp-for="ProjectObj.Status" class="form-label">Status</label>
                                                <select class="form-select" id="status" asp-for="ProjectObj.Status">
                                                    <option value="Update">Updated</option>
                                                    <option value="Draft">Draft</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div><!-- End Modal Form Modal-->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

<script>
    var projectModal = document.getElementById('projectModal');
    projectModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Nút đã kích hoạt modal
        var modalTitle = projectModal.querySelector('.modal-title');
        if (button.id === 'btnAddNew') {
            modalTitle.textContent = 'Add New Project';
            projectModal.querySelector('#projectId').value = '';
            projectModal.querySelector('#projectTitle').value = '';
            projectModal.querySelector('#projectBudget').value = '';
            projectModal.querySelector('#projectDuration').value = '';

            projectModal.querySelector('#statusGroup').classList.add('d-none');
            projectModal.querySelector('#status').value = '';
        } else {
            var id = button.getAttribute('data-id');
            var titleData = button.getAttribute('data-title');
            var budgetData = button.getAttribute('data-budget');
            var durationData = button.getAttribute('data-duration');

            modalTitle.textContent = 'Edit Project';
            projectModal.querySelector('#isEdit').value = 'true';
            projectModal.querySelector('#projectId').value = id;
            projectModal.querySelector('#projectTitle').value = titleData;
            projectModal.querySelector('#projectBudget').value = budgetData;
            projectModal.querySelector('#projectDuration').value = durationData;

            projectModal.querySelector('#statusGroup').classList.remove('d-none');
            projectModal.querySelector('#status').value = 'Update';
        }
    });
</script>

ChillLancer_RazorPage/ChillLancer_RazorPage/Pages/Admin/Management/Proposals.cshtml
@page
@model ChillLancer_RazorPage.Pages.Admin.Management.ProposalsModel
@{
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Categories Configuration</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-page="/Dashboard">Dashboard</a></li>
                <li class="breadcrumb-item">System Configuration</li>
                <li class="breadcrumb-item active">Categories</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Datatables</h5>
                        <p>Add lightweight datatables to your project with using the <a href="https://github.com/fiduswriter/Simple-DataTables" target="_blank">Simple DataTables</a> library. Just add <code>.datatable</code> class name to any table you wish to conver to a datatable. Check for <a href="https://fiduswriter.github.io/simple-datatables/demos/" target="_blank">more examples</a>.</p>

                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>
                                        Title
                                    </th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th data-type="date" data-format="YYYY/DD/MM">CreatedAt</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var prop in Model.Proposals)
                                {
                                    <tr>
                                        <td>@prop.Title</td>
                                        <td>@prop.Description</td>
                                        <td>@prop.Status</td>
                                        <td>@prop.CreatedAt</td>
                                        
                                        @* <td> *@
                                        @*     <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#propModal" *@
                                        @*             data-id="@prop.Id" data-nametag="@prop.Title" data-title="@prop.FullName" data-email="@prop.Email" *@
                                        @*             data-password="@prop.Password" data-identity="@prop.IdentityCode" data-phone="@prop.PhoneNumber" *@
                                        @*             data-address="@prop.Address" data-national="@prop.National" data-company="@prop.CompanyName" *@
                                        @*             data-isverified="@prop.IsVerified" data-role="@prop.Role" data-status="@prop.Status"> *@
                                        @*         Edit *@
                                        @*     </button> *@
                                        @*     <form method="post" asp-page-handler="Delete" style="display:inline"> *@
                                        @*         <input type="hidden" name="id" value="@prop.Id" /> *@
                                        @*         <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure to delete?')">Delete</button> *@
                                        @*     </form> *@
                                        @* </td> *@
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->